r"""
GimmeTools — release builder.

Produces, in dist/:
  GimmeTools/                          onedir app (GimmeTools.exe + runtime)
  GimmeTools-<ver>-portable-win64.zip  portable build
  GimmeTools-Setup.iss                 Inno Setup script
  GimmeTools-Setup-<ver>.exe           installer (only if iscc is on PATH)

Run with any Python 3.10+ that can pip-install:
    py install\build_release.py
    py install\build_release.py --skip-exe     (stage + zip from source only)

The exe is the app shell. The processing engine (venv with rembg/ONNX) is
provisioned on the user's machine by first-run setup, exactly like the
source distribution — this keeps the download small and GPU-correct.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "dist"
STAGE = DIST / "GimmeTools"

# Runtime trees shipped beside the exe (real folders, not bundled)
RUNTIME_DIRS = ["scripts", "install", "app/ui", "assets"]
RUNTIME_FILES = ["config/hb-preset.json", "README.md", "LICENSE", "GimmeTools.bat"]
EMPTY_DIRS = ["logs", "models", "outputs/tmp", "tools/ffmpeg", "tools/realesrgan", "data"]


def version() -> str:
    sys.path.insert(0, str(ROOT / "scripts"))
    from lib.config import VERSION
    return VERSION


def step(msg: str) -> None:
    print(f"\n[*] {msg}", flush=True)


def run(cmd: list, **kw) -> int:
    print("    $", " ".join(str(c) for c in cmd), flush=True)
    return subprocess.run([str(c) for c in cmd], **kw).returncode


def build_exe() -> bool:
    step("Building shell exe (PyInstaller)...")
    if run([sys.executable, "-m", "PyInstaller", "--version"],
           capture_output=True) != 0:
        print("    Installing pyinstaller...")
        if run([sys.executable, "-m", "pip", "install", "--user", "pyinstaller"]) != 0:
            print("    FAIL: could not install PyInstaller")
            return False

    rc = run([
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean", "--windowed",
        "--name", "GimmeTools",
        "--distpath", str(DIST),
        "--workpath", str(ROOT / "build"),
        "--specpath", str(ROOT / "build"),
        "--paths", str(ROOT),
        "--paths", str(ROOT / "scripts"),
        "--icon", str(ROOT / "assets" / "icon.ico"),
        "--add-data", f"{ROOT / 'app' / 'ui'};app/ui",
        "--add-data", f"{ROOT / 'assets'};assets",
        "--hidden-import", "webview.platforms.edgechromium",
        "--hidden-import", "webview.platforms.winforms",
        str(ROOT / "app" / "main.py"),
    ])
    if rc != 0 or not (STAGE / "GimmeTools.exe").exists():
        print("    FAIL: PyInstaller build did not produce GimmeTools.exe")
        return False
    print("    OK")
    return True


def stage_runtime(with_exe: bool) -> None:
    step("Staging runtime files...")
    STAGE.mkdir(parents=True, exist_ok=True)
    for rel in RUNTIME_DIRS:
        src, dst = ROOT / rel, STAGE / rel
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__"))
    for rel in RUNTIME_FILES:
        dst = STAGE / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / rel, dst)
    for rel in EMPTY_DIRS:
        (STAGE / rel).mkdir(parents=True, exist_ok=True)
    if not with_exe:
        # Source-only portable: app/ + the .bat is the entry point
        src, dst = ROOT / "app", STAGE / "app"
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__"))
    print(f"    OK: {STAGE}")


def make_zip(ver: str) -> Path:
    step("Zipping portable build...")
    out = DIST / f"GimmeTools-{ver}-portable-win64.zip"
    if out.exists():
        out.unlink()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(STAGE.rglob("*")):
            zf.write(path, Path("GimmeTools") / path.relative_to(STAGE))
    print(f"    OK: {out.name}  ({out.stat().st_size / 1024 / 1024:.1f} MB)")
    return out


ISS_TEMPLATE = r"""; GimmeTools installer — generated by install/build_release.py
; Build with Inno Setup 6:  iscc GimmeTools-Setup.iss

#define MyAppName "GimmeTools"
#define MyAppVersion "{VERSION}"
#define MyAppPublisher "Kaiden"
#define MyAppURL "https://github.com/imKaidenn/GimmeTools"
#define MyAppExeName "GimmeTools.exe"

[Setup]
AppId={{{{B7E8F3A1-4C2D-4E5F-9A8B-1D2C3E4F5A6B}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}/issues
DefaultDirName={{localappdata}}\GimmeTools
DefaultGroupName={{#MyAppName}}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=GimmeTools-Setup-{VERSION}
SetupIconFile=GimmeTools\assets\icon.ico
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={{app}}\{{#MyAppExeName}}

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; Flags: unchecked

[Files]
Source: "GimmeTools\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{{group}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"
Name: "{{userdesktop}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#MyAppName}}}}"; Flags: nowait postinstall skipifsilent
"""


def make_installer(ver: str) -> None:
    step("Installer script (Inno Setup)...")
    iss = DIST / "GimmeTools-Setup.iss"
    iss.write_text(ISS_TEMPLATE.format(VERSION=ver), encoding="utf-8")
    print(f"    OK: {iss.name}")
    if shutil.which("iscc"):
        step("Compiling installer with iscc...")
        if run(["iscc", str(iss)], cwd=str(DIST)) == 0:
            print("    OK: installer built")
        else:
            print("    WARN: iscc failed — see output above")
    else:
        print("    iscc not on PATH — install Inno Setup 6 and run:")
        print(f"      iscc {iss}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-exe", action="store_true",
                        help="skip PyInstaller; stage a source-based portable build")
    args = parser.parse_args()

    ver = version()
    print("=" * 50)
    print(f"  GimmeTools release builder — v{ver}")
    print("=" * 50)

    DIST.mkdir(exist_ok=True)
    with_exe = not args.skip_exe
    if with_exe and not build_exe():
        print("\n  Falling back to source-based portable build (--skip-exe).")
        with_exe = False

    stage_runtime(with_exe)
    make_zip(ver)
    if with_exe:
        make_installer(ver)

    print("\n" + "=" * 50)
    print("  Release artifacts are in dist\\")
    print("=" * 50)
    return 0


if __name__ == "__main__":
    sys.exit(main())
